### ISSUE TITLE
Clicking "Show optional information on one entry doesn't save it

### ISSUE THREAD

**Issue by roedoejet** [MotherTongues/mothertongues-UI#14]
create a service to remember the user's decision

**Comment by dhdaines** [comment]
Seems like using session storage for this would make sense (not sure that it should persist longer, that might be unexpected)

**Comment by roedoejet** [comment]
fixed by [d836c63](https://github.com/MotherTongues/mothertongues-UI/commit/d836c63dfb709a4ce6be9c5418c62067b0dd4e4a)
