### ISSUE TITLE
[mobile-ui] Pop up box is titled modal which is confusing

### ISSUE THREAD

**Issue by roedoejet** [MotherTongues/mothertongues-UI#15]

**Comment by roedoejet** [comment]
fixed by [a3fb35a](https://github.com/MotherTongues/mothertongues-UI/commit/a3fb35a598fa7deba9f1d97d8e36f51c06c00ba0)

**Comment by Maamashkaach** [comment]
The “Modal” title has been removed from the Browse popup, but is still there for the Search popup.
