### ISSUE TITLE
Search pop up box is titled modal

### ISSUE THREAD

**Issue by Maamashkaach** [MotherTongues/mothertongues-UI#24]
The “Modal” title has been removed from the Browse popup, but is still there for the Search popup.

_Originally posted by @Maamashkaach in https://github.com/MotherTongues/mothertongues-UI/issues/15#issuecomment-2094827669_

**Comment by roedoejet** [comment]
Thanks so much @Maamashkaach this is fixed now as of [2702827](https://github.com/MotherTongues/mothertongues-UI/commit/2702827a9bb6315f0a88ad7590a2f07d31c85b05)
