### ISSUE TITLE
Label Text Overwritten in Pop-up Box

### ISSUE THREAD

**Issue by Maamashkaach** [MotherTongues/mothertongues-UI#29]
When the “Show optional information” option is selected, the label text fields (on the left) in the pop-up box wrap when the information on the right is too long. This issue eventually causes the label/title text to be completely overwritten by the information on the right when it extends to a sufficient length.

Ideally, the label text fields on the left should remain visible and not be overwritten by the text on the right. Longer labels could wrap at word breaks, but in the example pictured the label that wrapped was the short word "Notes". If it isn't possible to stop the label from wrapping it would be preferable to remove the label rather than have it wrap on a letter-by-letter basis. 

![Screenshot 2024-05-29 at 6 43 12 AM](https://github.com/MotherTongues/mothertongues-UI/assets/116670922/2ebc2511-efd7-4549-9f51-26ce0d9b5f49)
![Screenshot 2024-05-29 at 7 14 42 AM](https://github.com/MotherTongues/mothertongues-UI/assets/116670922/c980defa-4bcd-44f0-bdcf-c8c0bdc2161a)
![Screenshot 2024-05-29 at 6 42 05 AM](https://github.com/MotherTongues/mothertongues-UI/assets/116670922/0e4d4c8f-2972-41ef-b0cd-587936001ba4)

**Comment by roedoejet** [comment]
Thanks so much @Maamashkaach ! I think this is now fixed as of [9144fb9](https://github.com/MotherTongues/mothertongues-UI/commit/9144fb9d88b987e4afdd0ca445888399385da936) but I still have to pull in the changes into the main repo. See screenshot below for the change I made: 

<img width="600" alt="image" src="https://github.com/MotherTongues/mothertongues-UI/assets/14815080/1524cdc7-bda3-434c-be9b-284c35fcdda9">
